### ISSUE TITLE
Add SocNet.Services and add endpoints to SocNet.WebAPI

### ISSUE THREAD

**Issue by IgorGribowsky** [IgorGribowsky/SocNet#3]
![image](https://user-images.githubusercontent.com/47255467/139541910-2c757a70-e4c4-44ea-b069-5909de4da4a4.png)

**Comment by grias** [comment]
Instead of `posts/fromUser/{id}` we could use something like `users/{id}/posts`

**Comment by grias** [comment]
[Few tips](https://www.merixstudio.com/blog/best-practices-rest-api-development/)

**Comment by grias** [comment]
[Best Practices for Designing a Pragmatic RESTful API](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api)
